ConnectFacebook:
    type: entity
    table: connect_facebook
    indexes:
        IDX_7C0FAFF4F8371B55:
            columns:
                - ID_USER
    uniqueConstraints:
        NewIndex1:
            columns:
                - ID_USER
                - ID_USER_FACEBOOK
        NewIndex2:
            columns:
                - ID_USER_FACEBOOK
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idUserFacebook:
            type: string
            nullable: true
            length: 72
            options:
                fixed: false
            column: ID_USER_FACEBOOK
        isconnect:
            type: boolean
            nullable: true
            column: ISCONNECT
        dataTime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: DATA_TIME
        offlineAccess:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: OFFLINE_ACCESS
        publicOut:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: PUBLIC_OUT
    manyToOne:
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_USER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
