CronFcbWall:
    type: entity
    table: cron_fcb_wall
    uniqueConstraints:
        FK_cron_fcb_wall:
            columns:
                - ID_USER
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        sendqueue:
            type: boolean
            nullable: true
            column: SENDQUEUE
        dataTime:
            type: datetime
            nullable: true
            column: DATA_TIME
        dataTimeSend:
            type: datetime
            nullable: true
            column: DATA_TIME_SEND
    manyToOne:
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_USER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
