FacebookUids:
    type: entity
    table: facebook_uids
    uniqueConstraints:
        NewIndex1:
            columns:
                - UID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ID_USER
        idFaceRel:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ID_FACE_REL
        uid:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: UID
        sendStatus:
            type: boolean
            nullable: true
            column: SEND_STATUS
    lifecycleCallbacks: {  }
