Lections:
    type: entity
    table: lections
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idLanguage:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ID_LANGUAGE
        idLangTranslate:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ID_LANG_TRANSLATE
        title:
            type: string
            nullable: true
            length: 258
            options:
                fixed: false
            column: TITLE
    lifecycleCallbacks: {  }
