Lerning:
    type: entity
    table: lerning
    indexes:
        FK_lerning2:
            columns:
                - ID_DICTIONARY
        IDX_BE0616E4F8371B55:
            columns:
                - ID_USER
    uniqueConstraints:
        NewIndex1:
            columns:
                - ID_USER
                - ID_LECTION
                - ID_DICTIONARY
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idLection:
            type: boolean
            nullable: false
            column: ID_LECTION
        idDictionary:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: ID_DICTIONARY
        wordStatus:
            type: boolean
            nullable: true
            column: WORD_STATUS
        repeadCount:
            type: boolean
            nullable: true
            column: REPEAD_COUNT
        exam:
            type: boolean
            nullable: true
            column: EXAM
        examBufor:
            type: boolean
            nullable: true
            column: EXAM_BUFOR
        answerOk:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ANSWER_OK
        answerErr:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ANSWER_ERR
    manyToOne:
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_USER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
