Params:
    type: entity
    table: params
    indexes:
        IDX_8FCE0EF3F8371B55:
            columns:
                - ID_USER
    uniqueConstraints:
        NewIndex1:
            columns:
                - ID_USER
                - PARAMS
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        params:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: PARAMS
        vals:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: VALS
    manyToOne:
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_USER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
