ParamSys:
    type: entity
    table: param_sys
    id:
        id:
            type: float
            nullable: false
            precision: 10
            scale: 0
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 96
            options:
                fixed: false
            column: NAME_
        value:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
            column: VALUE_
        description:
            type: string
            nullable: true
            length: 384
            options:
                fixed: false
            column: DESCRIPTION
    lifecycleCallbacks: {  }
