Session:
    type: entity
    table: session
    id:
        keyss:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            id: true
            column: KEYSS
            generator:
                strategy: IDENTITY
    fields:
        sessJson:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: SESS_JSON
    lifecycleCallbacks: {  }
