ShopOrder:
    type: entity
    table: shop_order
    uniqueConstraints:
        NewIndex1:
            columns:
                - IDS_SESSION
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        typ:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: TYP
        idUser:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ID_USER
        statusManual:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: STATUS_MANUAL
        email:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: EMAIL
        price:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: PRICE
        p24Metoda:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: P24_METODA
        paymentType:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: PAYMENT_TYPE
        partnumber:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
            column: PARTNUMBER
        dataTime:
            type: datetime
            nullable: true
            column: DATA_TIME
        p24OrderId:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: P24_ORDER_ID
        statusBackP24:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
                comment: 'null - nie wrocilo, 1 - OK, ERR:kod nledu'
            column: STATUS_BACK_P24
        statusBackP24Time:
            type: datetime
            nullable: true
            column: STATUS_BACK_P24_TIME
        statusVeryfP24:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
                comment: '1- OK, lub kod bledu'
            column: STATUS_VERYF_P24
        statusVeryfP24Time:
            type: datetime
            nullable: true
            column: STATUS_VERYF_P24_TIME
        nazwa1:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: NAZWA1
        adres1:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: ADRES1
        miejscowosc1:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: MIEJSCOWOSC1
        kod1:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
            column: KOD1
        fvat:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: FVAT
        nip:
            type: string
            nullable: true
            length: 19
            options:
                fixed: false
            column: NIP
        nazwa2:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: NAZWA2
        adres2:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: ADRES2
        kod2:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
            column: KOD2
        miejscowosc2:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: MIEJSCOWOSC2
        uwagi:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: UWAGI
        title:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: TITLE
        p24Clientid:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: P24_CLIENTID
        ppReceiverId:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: PP_RECEIVER_ID
        ppPaymentStatus:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
            column: PP_PAYMENT_STATUS
        ppPaymentDate:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
            column: PP_PAYMENT_DATE
        ppTxnId:
            type: string
            nullable: true
            length: 48
            options:
                fixed: false
            column: PP_TXN_ID
        ppPayerEmail:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: PP_PAYER_EMAIL
        idsSession:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
            column: IDS_SESSION
        ip:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: IP
        brow:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: BROW
    lifecycleCallbacks: {  }
