Stati:
    type: entity
    table: stati
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: CONTENT
        datatime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: DATATIME
        page:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
            column: PAGE
    lifecycleCallbacks: {  }
