Stickers:
    type: entity
    table: stickers
    indexes:
        IDX_D88DAC16F8371B55:
            columns:
                - ID_USER
    uniqueConstraints:
        NewIndex1:
            columns:
                - ID_USER
                - CONTENT
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        idUser2:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: ID_USER2
        statusRead:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: STATUS_READ
        data:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: DATA
        source:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: SOURCE
        position:
            type: string
            nullable: true
            length: 27
            options:
                fixed: false
            column: POSITION
        type:
            type: string
            nullable: true
            length: 3
            options:
                fixed: false
            column: TYPE
        content:
            type: string
            nullable: true
            length: 210
            options:
                fixed: false
            column: CONTENT
    manyToOne:
        idUser:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_USER:
                    referencedColumnName: ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
