<?php

namespace AppBundle\Repository;

/**
 * DupaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DupaRepository extends \Doctrine\ORM\EntityRepository
{
}
